import streamlit as st
from datetime import date
from datetime import datetime
from src.markets import get_all_prices
from src.news import get_headlines
from src.summarise import get_summary


# --- Page config ---
now = datetime.now()
today = now.strftime("%A %d %B %Y")
time = now.strftime("%H:%M")

st.set_page_config(
    page_title=f"Morning Macro Brief {today}",
    page_icon="📈",
    layout="wide"
)

# --- Caching ---
@st.cache_data(ttl="1h")
def load_prices():
    return get_all_prices()

@st.cache_data(ttl="1h")
def load_headlines():
    return get_headlines(max_per_feed=5)

@st.cache_data(ttl="1h")
def load_summary(prices, headlines):
    return get_summary(prices, headlines)


# --- Header ---
st.title(f"📈 Morning Macro Brief {today} {time}")
st.caption(f"Good morning! Here's your macroeconomic briefing :))")
st.divider()

# --- Markets ---
st.subheader("Markets")

prices = load_prices()

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric("FTSE 100", f"{prices.get('FTSE100', 'N/A'):,.0f}")
with col2:
    st.metric("GBP/USD", f"{prices.get('GBP/USD', 'N/A'):.4f}")
with col3:
    st.metric("Brent Crude", f"${prices.get('Brent Crude', 'N/A'):.2f}")
with col4:
    st.metric("US 10yr Yield", f"{prices.get('US 10yr Treasury Yield', 'N/A'):.2f}%")

st.divider()

# --- AI Briefing ---
st.subheader("AI Briefing")
st.caption("Generated by Llama 3.2 running locally via Ollama")

headlines = load_headlines()

with st.spinner("Generating your briefing... (this may take 20-30 seconds :) )"):
    summary = load_summary(prices, headlines)

st.write(summary)

st.divider()

# --- Headlines ---
st.subheader("Headlines")

for item in headlines:
    st.markdown(f"**[{item['title']}]({item['link']})** — *{item['source']}*")